Sprint 8 homework
SidorovKV/go-db-sql-final pull request #1
Opened 2024-01-18 19:25 UTC by SidorovKV

2024-01-18 20:31 UTC, just-musha requested changes
Привет! Отличная работа!
В последнем тесте что-то с условием - мб я не поняла, если что напиши плиз коментарий. Оставила предложение в комментарии, предлагаю поправить. Остальное все не критично.

2024-01-18 20:31 UTC, just-musha commented on parcel.go
> +		return nil, err
Можно кстати ещё врапать ошибки чтобы добавить больше контекста - например fmt.Errorf("get by client query error: %w", err)

https://rollbar.com/blog/golang-wrap-and-unwrap-error/

2024-01-18 20:31 UTC, just-musha commented on parcel.go
> +const (
Хорошее решение, супер читаемо

2024-01-18 20:31 UTC, just-musha commented on parcel_test.go
> +	require.Error(t, err)
Тут ещё можно проверить саму ошибку - что это `ErrNoRows`

2024-01-18 20:31 UTC, just-musha commented on parcel_test.go
> +		}
А здесь точно нужно это условие? 
Нам по ТЗ надо чтоб всегда было `оk` было true, и если нет то тест должен упасть. Как насчет использовать `require`?
И после уже поля сравнить

2024-01-19 07:11 UTC, SidorovKV commented on parcel_test.go
> +		}
Ага, спасибо. Упустил из виду, что require вызывает t.FailNow() при провале проверки

2024-01-19 07:59 UTC, just-musha approved these changes
Супер. Спасибо. Принято!

2024-03-02 18:31 UTC, merged